//import javax.swing.table.DefaultTableModel;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableColumn;
//import javax.swing.JTable;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import database.dbconnection;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wixx
 */
public class DASHBOARD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DASHBOARD.class.getName());
//    private NotifikasiManager notifikasiManager;

    public DASHBOARD() {
        initComponents();
        setLocationRelativeTo(null);
        updateProgressBar();
        
        barprogress = new javax.swing.JProgressBar();
        barprogress.setMaximum(250);
        barprogress.setMinimum(0);
        barprogress.setStringPainted(true); 
        Notifikasi.startGlobalTimer();
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        LAYAR_UTAMA = new javax.swing.JPanel();
        BAR_ATAS = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bdashboard = new javax.swing.JButton();
        bpengaturan = new javax.swing.JButton();
        btugas = new javax.swing.JButton();
        bskp = new javax.swing.JButton();
        wellcome_HOME = new javax.swing.JLabel();
        CAPTION1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldashboard = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        wellcome_HOME1 = new javax.swing.JLabel();
        barprogress = new javax.swing.JProgressBar();
        wellcome_HOME2 = new javax.swing.JLabel();
        CAPTION2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LAYAR_UTAMA.setBackground(new java.awt.Color(255, 255, 255));

        BAR_ATAS.setBackground(new java.awt.Color(51, 0, 153));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        bdashboard.setBackground(new java.awt.Color(51, 0, 153));
        bdashboard.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        bdashboard.setForeground(new java.awt.Color(204, 255, 255));
        bdashboard.setText("DASHBOARD");
        bdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdashboardActionPerformed(evt);
            }
        });

        bpengaturan.setBackground(new java.awt.Color(51, 0, 153));
        bpengaturan.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        bpengaturan.setForeground(new java.awt.Color(204, 255, 255));
        bpengaturan.setText("PENGATURAN");
        bpengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengaturanActionPerformed(evt);
            }
        });

        btugas.setBackground(new java.awt.Color(51, 0, 153));
        btugas.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        btugas.setForeground(new java.awt.Color(204, 255, 255));
        btugas.setText("TUGAS");
        btugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btugasActionPerformed(evt);
            }
        });

        bskp.setBackground(new java.awt.Color(51, 0, 153));
        bskp.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        bskp.setForeground(new java.awt.Color(204, 255, 255));
        bskp.setText("POIN SKP");
        bskp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bskpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BAR_ATASLayout = new javax.swing.GroupLayout(BAR_ATAS);
        BAR_ATAS.setLayout(BAR_ATASLayout);
        BAR_ATASLayout.setHorizontalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BAR_ATASLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btugas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bskp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(bpengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        BAR_ATASLayout.setVerticalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BAR_ATASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btugas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bskp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        wellcome_HOME.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellcome_HOME.setText("WELCOME TO AKTIVA");
        wellcome_HOME.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        CAPTION1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        CAPTION1.setForeground(new java.awt.Color(51, 0, 153));
        CAPTION1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAPTION1.setText("let me manage your work");
        CAPTION1.setToolTipText("");
        CAPTION1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tbldashboard.setAutoCreateRowSorter(true);
        tbldashboard.setBackground(new java.awt.Color(204, 204, 204));
        tbldashboard.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tbldashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nama Kegiatan ", "Tanggal & Waktu", "Jenis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldashboard);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(919, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        wellcome_HOME1.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME1.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME1.setText("Progres Poin SKP");
        wellcome_HOME1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        barprogress.setBackground(new java.awt.Color(204, 204, 204));
        barprogress.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        barprogress.setForeground(new java.awt.Color(0, 0, 0));
        barprogress.setStringPainted(true);

        wellcome_HOME2.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME2.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME2.setText("To Do List ");
        wellcome_HOME2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        CAPTION2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        CAPTION2.setForeground(new java.awt.Color(51, 0, 153));
        CAPTION2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CAPTION2.setText("Target 250 poin");
        CAPTION2.setToolTipText("");
        CAPTION2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout LAYAR_UTAMALayout = new javax.swing.GroupLayout(LAYAR_UTAMA);
        LAYAR_UTAMA.setLayout(LAYAR_UTAMALayout);
        LAYAR_UTAMALayout.setHorizontalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(wellcome_HOME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CAPTION1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LAYAR_UTAMALayout.createSequentialGroup()
                        .addComponent(BAR_ATAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                        .addComponent(barprogress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(wellcome_HOME2)
                    .addComponent(wellcome_HOME1)
                    .addComponent(CAPTION2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LAYAR_UTAMALayout.setVerticalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addComponent(BAR_ATAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(wellcome_HOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAPTION1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(wellcome_HOME2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wellcome_HOME1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAPTION2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barprogress, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdashboardActionPerformed
        DASHBOARD dashboard = new DASHBOARD();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bdashboardActionPerformed

    private void bpengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengaturanActionPerformed
        PENGATURAN pengaturan = new PENGATURAN();
        pengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bpengaturanActionPerformed

    private void btugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btugasActionPerformed
        TUGASpage kegiatan = new TUGASpage();
        kegiatan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btugasActionPerformed

    private void bskpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bskpActionPerformed
        POINskp poin = new POINskp();
        poin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bskpActionPerformed

    private void setupTable() {
        TableColumn idColumn = tbldashboard.getColumnModel().getColumn(0);
        idColumn.setMinWidth(0);
        idColumn.setMaxWidth(0);
        idColumn.setPreferredWidth(0);
        idColumn.setResizable(false);
    }


    
public void updateProgressBar() {
    try {
        Connection conn = dbconnection.getConnection();

        String sql = "SELECT SUM(poin) AS totalPoin FROM riwayat_skp WHERE id_user = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, sessionLogin.id_user);

        ResultSet rs = pst.executeQuery();

        int totalPoin = 0;
        if (rs.next()) {
            totalPoin = rs.getInt("totalPoin");
        }

        int target = 250;
        int progress = (int) ((totalPoin * 100.0) / target);

        barprogress.setValue(progress);
        barprogress.setString(progress + "%");

    } catch (Exception e) {
        System.out.println("Gagal update progress bar: " + e.getMessage());
    }
}


public void viewDataTableDashboard() {
        DefaultTableModel model = new DefaultTableModel(
        new String[]{"id", "Nama Kegiatan/Tugas", "Tanggal & Waktu", "Jenis"}, 
        0
    );

    try {
        Connection conn = dbconnection.getConnection();
        String sql = 
                    "SELECT id_kegA AS id, nama_tugas AS nama_kegiatan, deadline AS tanggalWaktu, 'Akademik' AS jenis " + 
                    "FROM kegiatan_akademik WHERE id_user = ? " +
                
                    "UNION ALL " +
                
                    "SELECT id_kegNA AS id, namaKegiatan AS nama_kegiatan, CAST(CONCAT(tgl_kegiatan, ' ', waktu_kegiatan) AS DATETIME) AS tanggalWaktu, 'Non Akademik' AS jenis " +
                    "FROM kegiatan_nonakademik WHERE id_user = ? " +
                
                    "ORDER BY tanggalWaktu ASC";

        PreparedStatement pst= conn.prepareStatement(sql);
        pst.setInt(1, sessionLogin.id_user);
        pst.setInt(2, sessionLogin.id_user);
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[] {
                rs.getInt("id"),
                rs.getString("nama_kegiatan"),
                rs.getString("tanggalWaktu"),
                rs.getString("jenis"),
            };
            model.addRow(row);
        }

        tbldashboard.setModel(model);
        setupTable();
        
        pst.close();
        rs.close();
        conn.close();

    } catch (SQLException e) {
        System.out.println("Error SQL: " + e.getMessage());
    }
    
//    SwingUtilities.invokeLater(() -> {
//    try {
//        viewDataTableDashboard();
//    } catch (Exception e) {
//        System.out.println("Gagal load data: " + e.getMessage());
//    }
//});
    

}
    
//    private int hitungTotalPoinSKP() {
//        int total = 0;
//        for (String[] data : POINskp.dataPOIN) {
//            try {
//                int poin = Integer.parseInt(data[2]);
//                total += poin;
//            } catch (NumberFormatException e) {
//                Sytem.err.println("Error parsing poin: " + data[2]);
//            }
//        }
//        return total;
//    }    
    
   
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            updateProgressBar();
            viewDataTableDashboard();
        }
    }    
    
   
//    protected void processWindowEvent(java.awt.event.WindowEvent e) {
//        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
//            if (notifikasiManager != null) {
//                notifikasiManager.stop();
//            }
//            super.processWindowEvent(e);
//        } else {
//            super.processWindowEvent(e);
//        }
//    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DASHBOARD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BAR_ATAS;
    private javax.swing.JLabel CAPTION1;
    private javax.swing.JLabel CAPTION2;
    private javax.swing.JPanel LAYAR_UTAMA;
    private javax.swing.JProgressBar barprogress;
    private javax.swing.JButton bdashboard;
    private javax.swing.JButton bpengaturan;
    private javax.swing.JButton bskp;
    private javax.swing.JButton btugas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldashboard;
    private javax.swing.JLabel wellcome_HOME;
    private javax.swing.JLabel wellcome_HOME1;
    private javax.swing.JLabel wellcome_HOME2;
    // End of variables declaration//GEN-END:variables
}
