
import javax.swing.JOptionPane;
import java.sql.*;
import database.dbconnection;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class LOGINpage extends javax.swing.JFrame {
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
   
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LOGINpage.class.getName());
    public static String registeredUser = "";
    public static String registeredPass = "";
    public static String namaUser = "";
    public static String npmUser = "";
    public static String fakultasUser = "";
    public static String prodiUser = "";
    public static String semesterUser = "";
    public static String kelasUser = "";
    public static String alamatUser = "";
    public static String lahirUser = "";
    /**
     * Creates new form LOGINpage
     */
    public LOGINpage() {
        initComponents();
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAYAR_UTAMA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        tpassword = new javax.swing.JPasswordField();
        tshow_password = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        blogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bregis = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LAYAR_UTAMA.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username   :");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BESTIE!!!");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sebelum itu login dulu yuk");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password   :");

        tuser.setBackground(new java.awt.Color(0, 0, 153));
        tuser.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tuser.setForeground(new java.awt.Color(204, 255, 255));

        tpassword.setBackground(new java.awt.Color(0, 0, 153));
        tpassword.setForeground(new java.awt.Color(255, 255, 255));
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });

        tshow_password.setBackground(new java.awt.Color(255, 255, 255));
        tshow_password.setFont(new java.awt.Font("Tw Cen MT", 1, 13)); // NOI18N
        tshow_password.setText("Show password");
        tshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tshow_passwordActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELLCOME BACK");

        blogin.setBackground(new java.awt.Color(102, 255, 255));
        blogin.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        blogin.setForeground(new java.awt.Color(0, 0, 153));
        blogin.setText("LOGIN");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        jLabel4.setText("Belum punya akun?");

        bregis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bregis.setText("Sign up");
        bregis.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        bregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout LAYAR_UTAMALayout = new javax.swing.GroupLayout(LAYAR_UTAMA);
        LAYAR_UTAMA.setLayout(LAYAR_UTAMALayout);
        LAYAR_UTAMALayout.setHorizontalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tshow_password, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tuser)
                                        .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bregis)
                        .addGap(308, 308, 308))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
            .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        LAYAR_UTAMALayout.setVerticalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(tshow_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bregis))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel6)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tshow_passwordActionPerformed
        if (tshow_password.isSelected()){
            tpassword.setEchoChar((char)0);
        }
        else {
            tpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_tshow_passwordActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
//        if (tuser.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Masukkkan Username dengan Benar");
//        }
//        else if(tpassword.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Masukkan Password dengan Benar");
        
        
     
            try {
            Connection conn = dbconnection.getConnection();
            String sql = "SELECT * FROM users WHERE registeredUser = ? AND registeredPass = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tuser.getText());
            pst.setString(2, new String(tpassword.getPassword()));
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()){
                
            sessionLogin.id_user = rs.getInt("id_user");
                
            registeredUser = rs.getString("registeredUser");
            registeredPass = rs.getString("registeredPass");
            namaUser = rs.getString("namaUser");
            
            JOptionPane.showMessageDialog(null, "Login Berhasil, Selamat datang " + registeredUser);

            DASHBOARD dashboard = new DASHBOARD();
            dashboard.setVisible(true);
            this.dispose();
            
            } else{
            jLabelError.setText("Username atau Password Salah!!");
            tuser.setText("");
            tpassword.setText("");
            }
            
            rs.close();
            pst.close();
            conn.close();
            
            }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat login: " + e.getMessage());
            }  
    

        
    }//GEN-LAST:event_bloginActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
    
    }//GEN-LAST:event_tpasswordActionPerformed

    private void bregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisActionPerformed
        REGISpage signup = new REGISpage();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bregisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOGINpage().setVisible(true));
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LAYAR_UTAMA;
    private javax.swing.JButton blogin;
    private javax.swing.JButton bregis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JCheckBox tshow_password;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
