import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JTable;
import java.sql.*;
import database.dbconnection;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wixx
 */
public class POINskp extends javax.swing.JFrame {
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POINskp.class.getName());
    /**
     * Creates new form POINskp
     */
    public POINskp() {
        initComponents();
        setLocationRelativeTo(null);
        viewData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAYAR_UTAMA = new javax.swing.JPanel();
        BAR_ATAS = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bdashboard = new javax.swing.JButton();
        bpengaturan = new javax.swing.JButton();
        btugas = new javax.swing.JButton();
        bskp = new javax.swing.JButton();
        wellcome_HOME = new javax.swing.JLabel();
        CAPTION1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblskp = new javax.swing.JTable();
        bhapus = new javax.swing.JButton();
        btambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LAYAR_UTAMA.setBackground(new java.awt.Color(255, 255, 255));

        BAR_ATAS.setBackground(new java.awt.Color(51, 0, 153));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        bdashboard.setBackground(new java.awt.Color(51, 0, 153));
        bdashboard.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        bdashboard.setForeground(new java.awt.Color(204, 255, 255));
        bdashboard.setText("DASHBOARD");
        bdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdashboardActionPerformed(evt);
            }
        });

        bpengaturan.setBackground(new java.awt.Color(51, 0, 153));
        bpengaturan.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        bpengaturan.setForeground(new java.awt.Color(204, 255, 255));
        bpengaturan.setText("PENGATURAN");
        bpengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengaturanActionPerformed(evt);
            }
        });

        btugas.setBackground(new java.awt.Color(51, 0, 153));
        btugas.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        btugas.setForeground(new java.awt.Color(204, 255, 255));
        btugas.setText("TUGAS");
        btugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btugasActionPerformed(evt);
            }
        });

        bskp.setBackground(new java.awt.Color(51, 0, 153));
        bskp.setFont(new java.awt.Font("Tw Cen MT", 3, 13)); // NOI18N
        bskp.setForeground(new java.awt.Color(204, 255, 255));
        bskp.setText("POIN SKP");
        bskp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bskpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BAR_ATASLayout = new javax.swing.GroupLayout(BAR_ATAS);
        BAR_ATAS.setLayout(BAR_ATASLayout);
        BAR_ATASLayout.setHorizontalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BAR_ATASLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btugas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(bskp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(bpengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        BAR_ATASLayout.setVerticalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BAR_ATASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btugas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bskp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        wellcome_HOME.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellcome_HOME.setText("POIN SKP");
        wellcome_HOME.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        CAPTION1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        CAPTION1.setForeground(new java.awt.Color(51, 0, 153));
        CAPTION1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAPTION1.setText("Semangat kejar poin skp nya ya!!");
        CAPTION1.setToolTipText("");
        CAPTION1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        tblskp.setBackground(new java.awt.Color(204, 204, 204));
        tblskp.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tblskp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nama Kegiatan", "Jenis & Kategori", "Poin SKP", "Tanggal Perolehan", "Masa Berlaku", "Bukti"
            }
        ));
        jScrollPane1.setViewportView(tblskp);

        bhapus.setBackground(new java.awt.Color(255, 0, 0));
        bhapus.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        btambah.setBackground(new java.awt.Color(0, 0, 153));
        btambah.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("+");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LAYAR_UTAMALayout = new javax.swing.GroupLayout(LAYAR_UTAMA);
        LAYAR_UTAMA.setLayout(LAYAR_UTAMALayout);
        LAYAR_UTAMALayout.setHorizontalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BAR_ATAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wellcome_HOME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CAPTION1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        LAYAR_UTAMALayout.setVerticalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addComponent(BAR_ATAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wellcome_HOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAPTION1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btambah, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdashboardActionPerformed
        DASHBOARD dashboard = new DASHBOARD();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bdashboardActionPerformed

    private void bpengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengaturanActionPerformed
        PENGATURAN pengaturan = new PENGATURAN();
        pengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bpengaturanActionPerformed

    private void btugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btugasActionPerformed
        TUGASpage kegiatan = new TUGASpage();
        kegiatan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btugasActionPerformed

    private void bskpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bskpActionPerformed
        POINskp poin = new POINskp();
        poin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bskpActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int[] selectedRow = tblskp.getSelectedRows();

        if(selectedRow.length == 0){
            JOptionPane.showMessageDialog(this, "Pilih minimal 1 baris yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
      
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus?", "Konfirmasi hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_NO_OPTION){
            try{
                Connection conn = dbconnection.getConnection();
                String sql = "DELETE FROM riwayat_skp WHERE id_skp = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                
                for(int row : selectedRow){
                    int id = Integer.parseInt(tblskp.getValueAt(row, 0).toString());
                    pst.setInt(1, id);
                    pst.executeUpdate();
                    notifyDashboardUpdate();
                }
                pst.close();
                conn.close();

                JOptionPane.showMessageDialog(this, "Berhasil menghapus " + selectedRow.length + " data!");
                viewData();
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        EDIT_POINskp edit = new EDIT_POINskp();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btambahActionPerformed
  
    private void setupTable(){
        TableColumn idColumn = tblskp.getColumnModel().getColumn(0);
        idColumn.setMinWidth(0);
        idColumn.setMaxWidth(0);
        idColumn.setPreferredWidth(0);
        idColumn.setResizable(false);
    }
    
    public void viewData() {
         DefaultTableModel model = new DefaultTableModel(null, 
            new String[] {
        "id", "Nama Kegiatan", "Jenis & Kategori",  "Poin SKP", "Tanggal Perolehan", "Masa Berlaku", "Bukti"
    });

    try {
        Connection conn = dbconnection.getConnection();
        String sql = 
                      "SELECT id_skp, nama, " +
                      "CONCAT(jenis, ' / ', kategori) AS jenisKategori, " +
                      "poin, tgl_perolehan, " +
                      "CASE " +
                      "WHEN masa_tanggal IS NOT NULL THEN DATE_FORMAT(masa_tanggal, '%d-%m-%Y') " +
                      "WHEN masa_durasi IS NOT NULL THEN CONCAT(masa_durasi, ' Tahun') " +
                      "WHEN masa_lifetime = 1 THEN 'Seumur Hidup / Tidak Ada' " +
                      "ELSE '-' " +
                      "END AS masaBerlaku, " +
                      "sertifikat " +
                      "FROM riwayat_skp WHERE id_user = ?";

        PreparedStatement pst= conn.prepareStatement(sql);
        pst.setInt(1, sessionLogin.id_user);
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[] {
                rs.getInt("id_skp"),
                rs.getString("nama"),
                rs.getString("jenisKategori"),
                rs.getInt("poin"),
                rs.getString("tgl_perolehan"),
                rs.getString("masaBerlaku"),
                rs.getString("sertifikat")
                
            };
            model.addRow(row);
        }

        tblskp.setModel(model);
        
        setupTable();
        
        pst.close();
        rs.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Gagal menampilkan data: " + e.getMessage());
    }
    }
    
       public void notifyDashboardUpdate() {
    java.awt.Window[] windows = java.awt.Window.getWindows();

    for (java.awt.Window window : windows) { 
        if (window instanceof DASHBOARD) { 
            DASHBOARD dash = (DASHBOARD) window;
            
            dash.updateProgressBar(); 
            return;
        }
    }
}
  

    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new POINskp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BAR_ATAS;
    private javax.swing.JLabel CAPTION1;
    private javax.swing.JPanel LAYAR_UTAMA;
    private javax.swing.JButton bdashboard;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bpengaturan;
    private javax.swing.JButton bskp;
    private javax.swing.JButton btambah;
    private javax.swing.JButton btugas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblskp;
    private javax.swing.JLabel wellcome_HOME;
    // End of variables declaration//GEN-END:variables
}
