/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.toedter.calendar.JDateChooser;
import java.sql.*;
import javax.swing.*;
import java.util.Date;
import javax.swing.JOptionPane;
import database.dbconnection;


/**
 *
 * @author wixx
 */
public class TUGAS_NonAkademik extends javax.swing.JFrame {
    
    Connection conn;
    
  
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TUGAS_NonAkademik.class.getName());

    private JSpinner jam;
    private JSpinner menit;
  
    
    
    public TUGAS_NonAkademik() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        //atur spinner
        SpinnerNumberModel jam = new SpinnerNumberModel(0, 0, 23, 1);
        JSpinnerJam.setModel(jam);
        
        SpinnerNumberModel menit = new SpinnerNumberModel(0, 0, 59, 1);
        JSpinnermenit.setModel(menit);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wellcome_HOME5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        LAYAR_UTAMA = new javax.swing.JPanel();
        BAR_ATAS = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        wellcome_HOME = new javax.swing.JLabel();
        CAPTION1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        wellcome_HOME1 = new javax.swing.JLabel();
        wellcome_HOME2 = new javax.swing.JLabel();
        wellcome_HOME3 = new javax.swing.JLabel();
        JSpinnerJam = new javax.swing.JSpinner();
        wellcome_HOME4 = new javax.swing.JLabel();
        TnamaKegiatan = new javax.swing.JTextField();
        wellcome_HOME6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btambah = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        wellcome_HOME7 = new javax.swing.JLabel();
        JSpinnermenit = new javax.swing.JSpinner();
        bbatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        wellcome_HOME5.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME5.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME5.setText("Deskripsi");
        wellcome_HOME5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TAMBAHKAN");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LAYAR_UTAMA.setBackground(new java.awt.Color(255, 255, 255));

        BAR_ATAS.setBackground(new java.awt.Color(51, 0, 153));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BAR_ATASLayout = new javax.swing.GroupLayout(BAR_ATAS);
        BAR_ATAS.setLayout(BAR_ATASLayout);
        BAR_ATASLayout.setHorizontalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BAR_ATASLayout.setVerticalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BAR_ATASLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        wellcome_HOME.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellcome_HOME.setText("TUGAS NON AKADEMIK");
        wellcome_HOME.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        CAPTION1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        CAPTION1.setForeground(new java.awt.Color(51, 0, 153));
        CAPTION1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAPTION1.setText("Ada aktivitas apanih??");
        CAPTION1.setToolTipText("");
        CAPTION1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        wellcome_HOME1.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME1.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        wellcome_HOME2.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME2.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME2.setText("Nama kegiatan");
        wellcome_HOME2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        wellcome_HOME3.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME3.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME3.setText("Tempat kegiatan");
        wellcome_HOME3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        JSpinnerJam.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        wellcome_HOME4.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME4.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME4.setText("Tanggal kegiatan");
        wellcome_HOME4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TnamaKegiatan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        wellcome_HOME6.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME6.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME6.setText("Deskripsi");
        wellcome_HOME6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        btambah.setBackground(new java.awt.Color(0, 0, 204));
        btambah.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("TAMBAHKAN");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        wellcome_HOME7.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME7.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME7.setText("Waktu");
        wellcome_HOME7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        JSpinnermenit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        bbatal.setBackground(new java.awt.Color(255, 0, 0));
        bbatal.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        bbatal.setForeground(new java.awt.Color(255, 255, 255));
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        jLabel1.setText("Jam");

        jLabel2.setText("Menit");

        javax.swing.GroupLayout LAYAR_UTAMALayout = new javax.swing.GroupLayout(LAYAR_UTAMA);
        LAYAR_UTAMA.setLayout(LAYAR_UTAMALayout);
        LAYAR_UTAMALayout.setHorizontalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BAR_ATAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wellcome_HOME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CAPTION1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wellcome_HOME3)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(wellcome_HOME6)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wellcome_HOME2)
                                    .addComponent(TnamaKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                        .addComponent(wellcome_HOME4)
                                        .addGap(40, 40, 40)
                                        .addComponent(wellcome_HOME1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(wellcome_HOME7))
                                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                                .addComponent(JSpinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JSpinnermenit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel1)
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel2)))))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LAYAR_UTAMALayout.setVerticalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addComponent(BAR_ATAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wellcome_HOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAPTION1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wellcome_HOME2)
                    .addComponent(wellcome_HOME1)
                    .addComponent(wellcome_HOME4)
                    .addComponent(wellcome_HOME7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addComponent(TnamaKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wellcome_HOME3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wellcome_HOME6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JSpinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JSpinnermenit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        String namaKegiatan = TnamaKegiatan.getText();
        String tempatKegiatan = jTextField1.getText();
        String deskripsi = jTextArea2.getText();
        java.util.Date tgl = jDateChooser1.getDate();
        int jam = (int) JSpinnerJam.getValue();
        int menit = (int) JSpinnermenit.getValue();
       
        try{
            
            if (tgl == null){
                JOptionPane.showMessageDialog(this, "Tanggalnya belum kamu pilih!");
                return;
            }
            
            if (namaKegiatan.isEmpty() || tempatKegiatan.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
            }
            
            //ubah ke strig biar bs ke db
            java.sql.Date sqltanggal = new java.sql.Date(tgl.getTime()); 
            java.sql.Time sqlwaktu = java.sql.Time.valueOf(String.format("%02d:%02d:00", jam, menit));
            
            Connection conn = new dbconnection().getConnection();
            
            int idUser = sessionLogin.id_user;

            String sql = "INSERT INTO kegiatan_nonAkademik (id_user, namaKegiatan, tgl_kegiatan, waktu_kegiatan, tempat_kegiatan, deskripsi) VALUES (?,?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setInt(1, idUser);
            pst.setString(2, namaKegiatan);
            pst.setDate(3, sqltanggal);
            pst.setTime(4, sqlwaktu);
            pst.setString(5, tempatKegiatan);
            pst.setString(6, deskripsi);
            
            pst.executeUpdate();
            notifyDashboardUpdate();
            JOptionPane.showMessageDialog(this, "Data kegiatan berhasil disimpan!");
            
            TnamaKegiatan.setText("");
            jTextField1.setText("");
            jTextArea2.setText("");
            jDateChooser1.setDate(null);
            JSpinnerJam.setValue(0);
            JSpinnermenit.setValue(0);
            
            pst.close();
            conn.close();
            
            TUGASpage tambah = new TUGASpage();
            tambah.setVisible(true);
             this.dispose();
            
            
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }
        
     
    }//GEN-LAST:event_btambahActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
            TnamaKegiatan.setText("");
            jTextField1.setText("");
            jTextArea2.setText("");
            jDateChooser1.setDate(null);
            JSpinnerJam.setValue(0);
            JSpinnermenit.setValue(0);
            
            TUGASpage kegiatan = new TUGASpage();
             kegiatan.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_bbatalActionPerformed

     public void notifyDashboardUpdate() {
    java.awt.Window[] windows = java.awt.Window.getWindows();

    for (java.awt.Window window : windows) { 
        if (window instanceof DASHBOARD) { 
            DASHBOARD dash = (DASHBOARD) window;
            
            dash.viewDataTableDashboard();
            
            return;
        }
    }
} 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TUGAS_NonAkademik().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BAR_ATAS;
    private javax.swing.JLabel CAPTION1;
    private javax.swing.JSpinner JSpinnerJam;
    private javax.swing.JSpinner JSpinnermenit;
    private javax.swing.JPanel LAYAR_UTAMA;
    private javax.swing.JTextField TnamaKegiatan;
    private javax.swing.JButton bbatal;
    private javax.swing.JButton btambah;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JLabel wellcome_HOME;
    private javax.swing.JLabel wellcome_HOME1;
    private javax.swing.JLabel wellcome_HOME2;
    private javax.swing.JLabel wellcome_HOME3;
    private javax.swing.JLabel wellcome_HOME4;
    private javax.swing.JLabel wellcome_HOME5;
    private javax.swing.JLabel wellcome_HOME6;
    private javax.swing.JLabel wellcome_HOME7;
    // End of variables declaration//GEN-END:variables
}
