/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.toedter.calendar.JDateChooser;
import java.sql.*;
import javax.swing.*;
import java.util.Date;
import javax.swing.*;
import database.dbconnection;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author wixx
 */
public class TUGAS_Akademik extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TUGAS_Akademik.class.getName());

    
    private JSpinner jam;
    private JSpinner menit;
    
    public TUGAS_Akademik() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        SpinnerNumberModel jam = new SpinnerNumberModel(0, 0, 23, 1);
        jSpinnerjam.setModel(jam);
        
        SpinnerNumberModel menit = new SpinnerNumberModel(0, 0, 59, 1);
        jSpinnermenit.setModel(menit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAYAR_UTAMA = new javax.swing.JPanel();
        BAR_ATAS = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        wellcome_HOME = new javax.swing.JLabel();
        CAPTION1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TmataKuliah = new javax.swing.JTextField();
        wellcome_HOME1 = new javax.swing.JLabel();
        wellcome_HOME2 = new javax.swing.JLabel();
        wellcome_HOME3 = new javax.swing.JLabel();
        jSpinnermenit = new javax.swing.JSpinner();
        wellcome_HOME4 = new javax.swing.JLabel();
        TnmKegiatan = new javax.swing.JTextField();
        wellcome_HOME5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdeskripsi = new javax.swing.JTextArea();
        btambah = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinnerjam = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LAYAR_UTAMA.setBackground(new java.awt.Color(255, 255, 255));

        BAR_ATAS.setBackground(new java.awt.Color(51, 0, 153));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BAR_ATASLayout = new javax.swing.GroupLayout(BAR_ATAS);
        BAR_ATAS.setLayout(BAR_ATASLayout);
        BAR_ATASLayout.setHorizontalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BAR_ATASLayout.setVerticalGroup(
            BAR_ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BAR_ATASLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        wellcome_HOME.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellcome_HOME.setText("TUGAS AKADEMIK");
        wellcome_HOME.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        CAPTION1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        CAPTION1.setForeground(new java.awt.Color(51, 0, 153));
        CAPTION1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAPTION1.setText("Jangan sampe lewat deadlinenya ya!!");
        CAPTION1.setToolTipText("");
        CAPTION1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        TmataKuliah.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        wellcome_HOME1.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME1.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME1.setText("Waktu");
        wellcome_HOME1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        wellcome_HOME2.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME2.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME2.setText("Nama tugas");
        wellcome_HOME2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        wellcome_HOME3.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME3.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME3.setText("Matakuliah");
        wellcome_HOME3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSpinnermenit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        wellcome_HOME4.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME4.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME4.setText("Tanggal ");
        wellcome_HOME4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TnmKegiatan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        wellcome_HOME5.setBackground(new java.awt.Color(51, 0, 153));
        wellcome_HOME5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        wellcome_HOME5.setForeground(new java.awt.Color(51, 0, 153));
        wellcome_HOME5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellcome_HOME5.setText("Deskripsi");
        wellcome_HOME5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Tdeskripsi.setColumns(20);
        Tdeskripsi.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Tdeskripsi.setRows(5);
        jScrollPane1.setViewportView(Tdeskripsi);

        btambah.setBackground(new java.awt.Color(0, 0, 204));
        btambah.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("TAMBAHKAN");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        jSpinnerjam.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jSpinnerjam.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Jam");

        jLabel2.setText("Menit");

        bbatal.setBackground(new java.awt.Color(255, 0, 0));
        bbatal.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        bbatal.setForeground(new java.awt.Color(255, 255, 255));
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LAYAR_UTAMALayout = new javax.swing.GroupLayout(LAYAR_UTAMA);
        LAYAR_UTAMA.setLayout(LAYAR_UTAMALayout);
        LAYAR_UTAMALayout.setHorizontalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BAR_ATAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wellcome_HOME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CAPTION1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wellcome_HOME2)
                            .addComponent(TnmKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wellcome_HOME4)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                                .addComponent(jSpinnerjam, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnermenit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                                .addComponent(wellcome_HOME1)
                                .addGap(72, 72, 72))))
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wellcome_HOME3)
                            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wellcome_HOME5)
                                    .addComponent(TmataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        LAYAR_UTAMALayout.setVerticalGroup(
            LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                .addComponent(BAR_ATAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wellcome_HOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAPTION1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(wellcome_HOME2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(wellcome_HOME1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wellcome_HOME4)))
                .addGap(8, 8, 8)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TnmKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerjam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnermenit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wellcome_HOME3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TmataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wellcome_HOME5)
                .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYAR_UTAMALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYAR_UTAMALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LAYAR_UTAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LAYAR_UTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        String namaTugas = TnmKegiatan.getText();
        String mataKuliah = TmataKuliah.getText();
        String deskripsi = Tdeskripsi.getText();
        java.util.Date tgl = jDateChooser1.getDate();
        int jam = (int) jSpinnerjam.getValue();
        int menit = (int) jSpinnermenit.getValue();
        
        
         try{
            
            if (tgl == null){
                JOptionPane.showMessageDialog(this, "Tanggalnya belum kamu pilih!");
                return;
            }
            
            if (namaTugas.isEmpty() || mataKuliah.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
            }
            
          
            java.util.Calendar klndr = java.util.Calendar.getInstance();
            klndr.setTime(tgl);
            klndr.set(java.util.Calendar.HOUR_OF_DAY, jam);
            klndr.set(java.util.Calendar.MINUTE, menit);
            klndr.set(java.util.Calendar.SECOND, 0);
            
            java.sql.Timestamp deadline = new java.sql.Timestamp(klndr.getTimeInMillis());
           
            Connection conn = new dbconnection().getConnection();
            
            int idUser = sessionLogin.id_user;
            
            String sql = "INSERT INTO kegiatan_akademik (id_user, nama_tugas, mata_kuliah, deadline, deskripsi) VALUES (?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setInt(1, idUser);
            pst.setString(2, namaTugas);
            pst.setString(3, mataKuliah);
            pst.setTimestamp(4, deadline);
            pst.setString(5, deskripsi);
        
            
            pst.executeUpdate();
            notifyDashboardUpdate();
            JOptionPane.showMessageDialog(this, "Data kegiatan berhasil disimpan!");
            
            
             TnmKegiatan.setText("");
             TmataKuliah.setText("");
             Tdeskripsi.setText("");
             jDateChooser1.setDate(null);
             jSpinnerjam.setValue(0);
             jSpinnermenit.setValue(0);
             
             pst.close();
             conn.close();
             
             TUGASpage tambah = new TUGASpage();
             tambah.setVisible(true);
             this.dispose();
            
             
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }
         
    }//GEN-LAST:event_btambahActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
           TnmKegiatan.setText("");
             TmataKuliah.setText("");
             Tdeskripsi.setText("");
             jDateChooser1.setDate(null);
             jSpinnerjam.setValue(0);
             jSpinnermenit.setValue(0);
             
             TUGASpage kegiatan = new TUGASpage();
             kegiatan.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_bbatalActionPerformed

 


    
 public void notifyDashboardUpdate() {
    java.awt.Window[] windows = java.awt.Window.getWindows();

    for (java.awt.Window window : windows) { 
        if (window instanceof DASHBOARD) { 
            DASHBOARD dash = (DASHBOARD) window;
            
            dash.viewDataTableDashboard();
            
            return;
        }
    }
} 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TUGAS_Akademik().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BAR_ATAS;
    private javax.swing.JLabel CAPTION1;
    private javax.swing.JPanel LAYAR_UTAMA;
    private javax.swing.JTextArea Tdeskripsi;
    private javax.swing.JTextField TmataKuliah;
    private javax.swing.JTextField TnmKegiatan;
    private javax.swing.JButton bbatal;
    private javax.swing.JButton btambah;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerjam;
    private javax.swing.JSpinner jSpinnermenit;
    private javax.swing.JLabel wellcome_HOME;
    private javax.swing.JLabel wellcome_HOME1;
    private javax.swing.JLabel wellcome_HOME2;
    private javax.swing.JLabel wellcome_HOME3;
    private javax.swing.JLabel wellcome_HOME4;
    private javax.swing.JLabel wellcome_HOME5;
    // End of variables declaration//GEN-END:variables
}
